//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesGastro.Home {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logon() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesGastro.Home.Logon", typeof(Logon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mailadresse ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angabe erforderlich ähnelt.
        /// </summary>
        public static string ErrorPasswort {
            get {
                return ResourceManager.GetString("ErrorPasswort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angabe erforderlich ähnelt.
        /// </summary>
        public static string ErrorUsername {
            get {
                return ResourceManager.GetString("ErrorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank für Ihr Interesse an unsrem Angebot. Im Folgenden informieren wir Sie über den Umgang mit Ihren personenbezogenen Daten bei der Nutzung unserer Website. Diese erheben wir lediglich bei einer Kontaktanfrage an uns oder wenn Sie eine Anfrage wegen einer Veranstaltung an uns übermitteln. Die Daten werden lediglich zur Beantwortung genutzt und dann gelöscht. ähnelt.
        /// </summary>
        public static string ImpressumEinleitung {
            get {
                return ResourceManager.GetString("ImpressumEinleitung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn Sie unsere Website aufrufen, erheben wir lediglich die Verbindungsdaten Ihrer Anfrage (eigentlich werden sie automatisch aus einer technischen Notwendigkeit auf dem Webserver gespeichert). Diese sind technisch erforderlich, um Ihnen die Website anzuzeigen. ähnelt.
        /// </summary>
        public static string ImpressumTextMitte {
            get {
                return ResourceManager.GetString("ImpressumTextMitte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Server-Logfiles werden von uns nicht verarbeitet! Auch verwenden wir keine Cookies, um Informationen zu sammeln. ähnelt.
        /// </summary>
        public static string ImpressumTextUnten {
            get {
                return ResourceManager.GetString("ImpressumTextUnten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verantwortlich für die Inhalte der Webseite und die damit verbundene Datenverarbeitung im Sinne der Datenschutz-Grundverordnung (DSGVO) ist ähnelt.
        /// </summary>
        public static string ImpressumTextVerantwortlich {
            get {
                return ResourceManager.GetString("ImpressumTextVerantwortlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank für Ihr Interesse! Wir sind immer dankbar für Kritik, ob positiv oder negativ. Haben Sie Kontaktdaten hinterlegt beantworten wir natürlich auch gerne Ihre Fragen. ähnelt.
        /// </summary>
        public static string KontaktBestätigung {
            get {
                return ResourceManager.GetString("KontaktBestätigung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte melden Sie sich mit Mailadresse und Passwort an ähnelt.
        /// </summary>
        public static string Logintext {
            get {
                return ResourceManager.GetString("Logintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string Passwort {
            get {
                return ResourceManager.GetString("Passwort", resourceCulture);
            }
        }
    }
}
