//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesGastro.Shared {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navi() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesGastro.Shared.Navi", typeof(Navi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse ähnelt.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss sich um eine gültige Mailadresse handeln. ähnelt.
        /// </summary>
        public static string AlertMail {
            get {
                return ResourceManager.GetString("AlertMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie oben im Formular eine Personenzahl ein. ähnelt.
        /// </summary>
        public static string AlertPersonenzahl {
            get {
                return ResourceManager.GetString("AlertPersonenzahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte nur Ziffern eingeben. ähnelt.
        /// </summary>
        public static string AlertTelefon {
            get {
                return ResourceManager.GetString("AlertTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhaltsstoffe ähnelt.
        /// </summary>
        public static string Allergene {
            get {
                return ResourceManager.GetString("Allergene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gleichzeitig als unverbindliche Anfrage an den Wirt senden ähnelt.
        /// </summary>
        public static string AnfrageWirt {
            get {
                return ResourceManager.GetString("AnfrageWirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pdf erstellen ähnelt.
        /// </summary>
        public static string BtnPdfErstellenText {
            get {
                return ResourceManager.GetString("BtnPdfErstellenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Senden ähnelt.
        /// </summary>
        public static string BtnSendenText {
            get {
                return ResourceManager.GetString("BtnSendenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dienstag ähnelt.
        /// </summary>
        public static string Dienstag {
            get {
                return ResourceManager.GetString("Dienstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donnerstag ähnelt.
        /// </summary>
        public static string Donnerstag {
            get {
                return ResourceManager.GetString("Donnerstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich bin damit einverstanden, dass meine Angaben verwendet werden, damit auf meine Anfrage reagiert werden kann. Meine Daten werden sonst nicht verwendet und nach Ablauf des Reservierungstermins automatisch gelöscht. ähnelt.
        /// </summary>
        public static string DsvgoReservierung {
            get {
                return ResourceManager.GetString("DsvgoReservierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich bin damit einverstanden, dass meine Angaben verwendet werden, damit auf meine Anfrage reagiert werden kann. Meine Daten werden in keiner Datenbank gespeichert, sie werden lediglich auf das Pdf-Dokument gedruckt, das dem Veranstalter zugeht. ähnelt.
        /// </summary>
        public static string DsvgoText {
            get {
                return ResourceManager.GetString("DsvgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die durchgehend ähnelt.
        /// </summary>
        public static string durchgehend {
            get {
                return ResourceManager.GetString("durchgehend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mailadresse ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freitag ähnelt.
        /// </summary>
        public static string Freitag {
            get {
                return ResourceManager.GetString("Freitag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getränke ähnelt.
        /// </summary>
        public static string Getränke {
            get {
                return ResourceManager.GetString("Getränke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        public static string Impressum {
            get {
                return ResourceManager.GetString("Impressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu den News ähnelt.
        /// </summary>
        public static string IndexNewsBtnText {
            get {
                return ResourceManager.GetString("IndexNewsBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte haben Sie Verständnis, dass wir unsere News nicht in andere Sprachen übersetzen. ähnelt.
        /// </summary>
        public static string IndexNewsNoT {
            get {
                return ResourceManager.GetString("IndexNewsNoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt nur ein ich, bald ein Team! ähnelt.
        /// </summary>
        public static string IndexTeamHeader {
            get {
                return ResourceManager.GetString("IndexTeamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen zur kulinarischen Vita und zum Werdegang des neuen Inhabers Alexander Hert finden Sie auf unserer Teams-Seite. ähnelt.
        /// </summary>
        public static string IndexTeamText {
            get {
                return ResourceManager.GetString("IndexTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wann immer Sie einen schönen Abend in gemütlicher Atmosphäre bei einem                      ausgezeichneten Essen und Getränken verbringen möchten: ähnelt.
        /// </summary>
        public static string IndexText1 {
            get {
                return ResourceManager.GetString("IndexText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir sind für Sie da! ähnelt.
        /// </summary>
        public static string IndexText2 {
            get {
                return ResourceManager.GetString("IndexText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seit dem Ende des 19. Jahrhunderts wird dieses Ende des 18. Jahrhunderts erbaute Haus für gastronomische Zwecke genutzt.                        &quot;Der größte Saal am Platze&quot; entwickelte sich laut dem Einwohneradressbuch von Bergheim aus dem Jahre 1898 schnell zur &quot;bekanntesten Erholungsstation für Radfahrer&quot;. Schon damals wurde der Gasthof Zur Glocke von zahlreichen Vereinen für Veranstaltungen und Karnevalsbälle genutzt. Diese lange Tradition wird ab dem 01.06.2020 von Alexander Hert fortgesetzt. ähnelt.
        /// </summary>
        public static string IndexText3 {
            get {
                return ResourceManager.GetString("IndexText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zur aktuellen Umfrage ähnelt.
        /// </summary>
        public static string IndexUmfrageBtnText {
            get {
                return ResourceManager.GetString("IndexUmfrageBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zur Umfrageseite ähnelt.
        /// </summary>
        public static string IndexUmfrageBtnText2 {
            get {
                return ResourceManager.GetString("IndexUmfrageBtnText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelle Umfrage ähnelt.
        /// </summary>
        public static string IndexUmfrageHeader {
            get {
                return ResourceManager.GetString("IndexUmfrageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umfragen ähnelt.
        /// </summary>
        public static string IndexUmfrageHeader2 {
            get {
                return ResourceManager.GetString("IndexUmfrageHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auch unsere Umfragen werden nicht in andere Sprachen übersetzt. ähnelt.
        /// </summary>
        public static string IndexUmfrageNoT {
            get {
                return ResourceManager.GetString("IndexUmfrageNoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir haben wieder eine aktuelle Umfrage zu uns und unserem Angebot. Wir bitten Sie um Ihre Hilfe und/oder Ihre Meinung. ähnelt.
        /// </summary>
        public static string IndexUmfrageText {
            get {
                return ResourceManager.GetString("IndexUmfrageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An dieser Stelle präsentieren wir Ihnen in unregelmässigen Abständen Umfragen zu unserem Angebot. Bitte besuchen Sie unsere Seite bald wieder. ähnelt.
        /// </summary>
        public static string IndexUmfrageTextKeineUmfrage {
            get {
                return ResourceManager.GetString("IndexUmfrageTextKeineUmfrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhaber ähnelt.
        /// </summary>
        public static string Inhaber {
            get {
                return ResourceManager.GetString("Inhaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die insgesamt ähnelt.
        /// </summary>
        public static string Insgesamt {
            get {
                return ResourceManager.GetString("Insgesamt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Moment haben wir nichts Neues. Schauen Sie bald wieder rein. ähnelt.
        /// </summary>
        public static string KeineAktuellenNews {
            get {
                return ResourceManager.GetString("KeineAktuellenNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakt ähnelt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittagstisch ähnelt.
        /// </summary>
        public static string Mittagstisch {
            get {
                return ResourceManager.GetString("Mittagstisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falls Sie noch eine Nachricht oder Mitteilung für uns haben, benutzen Sie bitte das Textfeld. ähnelt.
        /// </summary>
        public static string MitteilungAnWirt {
            get {
                return ResourceManager.GetString("MitteilungAnWirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittwoch ähnelt.
        /// </summary>
        public static string Mittwoch {
            get {
                return ResourceManager.GetString("Mittwoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Montag ähnelt.
        /// </summary>
        public static string Montag {
            get {
                return ResourceManager.GetString("Montag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnungszeiten ähnelt.
        /// </summary>
        public static string Öffnungszeiten {
            get {
                return ResourceManager.GetString("Öffnungszeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank für Ihr Interesse an unserem Haus. Wir werden uns zeitnah mit Ihnen in Verbindung setzen. ähnelt.
        /// </summary>
        public static string PdfAnsprache {
            get {
                return ResourceManager.GetString("PdfAnsprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personen ähnelt.
        /// </summary>
        public static string Personen {
            get {
                return ResourceManager.GetString("Personen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Auswahl ähnelt.
        /// </summary>
        public static string PlanderPdfHeader {
            get {
                return ResourceManager.GetString("PlanderPdfHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit diesem Service können Sie die zu erwartenden Kosten für eine Veranstaltung berechnen und sich das Ergebnis ausdrucken. Wenn Sie möchten, können Sie Ihre Berechnung auch an den Wirt senden. Dann bitten wir Sie um ein paar Angaben, um Sie kontaktieren zu können. ähnelt.
        /// </summary>
        public static string PlanerBeschreibung {
            get {
                return ResourceManager.GetString("PlanerBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie zunächst die Anzahl der Personen ein, für die Sie eine Veranstaltung bei uns planen möchten. ähnelt.
        /// </summary>
        public static string PlanerIntro {
            get {
                return ResourceManager.GetString("PlanerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlanerPdfName {
            get {
                return ResourceManager.GetString("PlanerPdfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefonnummer ähnelt.
        /// </summary>
        public static string PlanerPdfTelefon {
            get {
                return ResourceManager.GetString("PlanerPdfTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geplanter Termin ähnelt.
        /// </summary>
        public static string PlanerPdfTermin {
            get {
                return ResourceManager.GetString("PlanerPdfTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summe ähnelt.
        /// </summary>
        public static string Planersumme {
            get {
                return ResourceManager.GetString("Planersumme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Räumlichkeiten ähnelt.
        /// </summary>
        public static string Raeumlichkeiten {
            get {
                return ResourceManager.GetString("Raeumlichkeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reservierung ähnelt.
        /// </summary>
        public static string Reservierung {
            get {
                return ResourceManager.GetString("Reservierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank für Ihre Reservierung. Wir freuen uns auf Sie! ähnelt.
        /// </summary>
        public static string ReservierungBestätigung {
            get {
                return ResourceManager.GetString("ReservierungBestätigung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restaurant ähnelt.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ruhetag ähnelt.
        /// </summary>
        public static string Ruhetag {
            get {
                return ResourceManager.GetString("Ruhetag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samstag ähnelt.
        /// </summary>
        public static string Samstag {
            get {
                return ResourceManager.GetString("Samstag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonntag ähnelt.
        /// </summary>
        public static string Sonntag {
            get {
                return ResourceManager.GetString("Sonntag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speisekarte ähnelt.
        /// </summary>
        public static string Speisekarte {
            get {
                return ResourceManager.GetString("Speisekarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speisen ähnelt.
        /// </summary>
        public static string Speisen {
            get {
                return ResourceManager.GetString("Speisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo, mein Name ist Alexander Hert, ich möchte mich hier kurz vorstellen. ähnelt.
        /// </summary>
        public static string Teams1 {
            get {
                return ResourceManager.GetString("Teams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich wurde 1983 in Nowosibirsk geboren und zog 1989 nach Erftstadt. Nach Schule und Abitur begann ich ein Studium zum Ingenieur Maschinenbau an der RWTH Aachen, stellte jedoch im Laufe der Zeit fest, dass ich lieber kochen will. Also entschloss ich mich nach 6 Semestern die Uni Uni sein zu lassen und das Kochen richtig zu erlernen. ähnelt.
        /// </summary>
        public static string Teams2 {
            get {
                return ResourceManager.GetString("Teams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Ausbildung zum Koch absolvierte ich im &apos;Seehotel Überfahrt&apos; in Rottach-Egern und bin ein wenig stolz darauf, die Ausbildung mit der besten Prüfung des Jahrgangs in Bayern abgeschlossen zu haben. Dort entwickelte ich auch meine Liebe zur bayrischen Küche. ähnelt.
        /// </summary>
        public static string Teams3 {
            get {
                return ResourceManager.GetString("Teams3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach meiner Ausbildung arbeitete ich im mittlerweile leider geschlossenen Husarenquartier (1* Michelin) bei &apos;Herbert Brockel&apos; und später im Hotel &apos;Elisenhof &apos; in Mönchengladbach jeweils als Garde Manger (Commis de Cuisine). ähnelt.
        /// </summary>
        public static string Teams4 {
            get {
                return ResourceManager.GetString("Teams4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es zog mich aber wieder nach Bayern, wo ich im &apos;Alpenhof&apos; in Murnau mit &apos;Thilo Bischoff&apos; zusammen arbeiten durfte. In dieser Zeit erlangte der &apos;Alpenhof&apos; seinen im Vorjahr verlorenen Michelinstern zurück, ein schönes Erlebnis. ähnelt.
        /// </summary>
        public static string Teams5 {
            get {
                return ResourceManager.GetString("Teams5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Anschluss verbrachte ich ein Jahr in der Schweiz, wo ich eine Sommer- und Wintersaison die Feinheiten des Schweizer Hotelbetriebs im Hotel &apos;Frutt&apos; in Melchsee kennen lernen durfte.
        ///Den krönenden Abschluss meiner &apos;Lehrjahre&apos; verbrachte ich als Nachtkoch auf der &apos;MS Europa&apos;. Dort reifte der Entschluss, mich selbständig zu machen, den ich mir dann im Tennisclub Königsdorf -TCK- erfüllen durfte. Dort hatte ich zwei wunderschöne Jahre, die meinen Entschluss bestätigt haben, mich direkt mit dem Gast zu befass [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Teams6 {
            get {
                return ResourceManager.GetString("Teams6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben nun in der Glocke das Resultat dieser Reise zur Verfügung. Guten Appetit! ähnelt.
        /// </summary>
        public static string Teams7 {
            get {
                return ResourceManager.GetString("Teams7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefax ähnelt.
        /// </summary>
        public static string Telefax {
            get {
                return ResourceManager.GetString("Telefax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über uns ähnelt.
        /// </summary>
        public static string UeberUns {
            get {
                return ResourceManager.GetString("UeberUns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uhr ähnelt.
        /// </summary>
        public static string Uhr {
            get {
                return ResourceManager.GetString("Uhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uhrzeit ähnelt.
        /// </summary>
        public static string Uhrzeit {
            get {
                return ResourceManager.GetString("Uhrzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und ähnelt.
        /// </summary>
        public static string und {
            get {
                return ResourceManager.GetString("und", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unser Team ähnelt.
        /// </summary>
        public static string UnserTeam {
            get {
                return ResourceManager.GetString("UnserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veranstaltungsplaner ähnelt.
        /// </summary>
        public static string Veranstaltungsplaner {
            get {
                return ResourceManager.GetString("Veranstaltungsplaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von ähnelt.
        /// </summary>
        public static string von {
            get {
                return ResourceManager.GetString("von", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen!!! ähnelt.
        /// </summary>
        public static string Willkommen {
            get {
                return ResourceManager.GetString("Willkommen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusammenfassung ähnelt.
        /// </summary>
        public static string Zusammenfassung {
            get {
                return ResourceManager.GetString("Zusammenfassung", resourceCulture);
            }
        }
    }
}
