//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesGastro.Shared {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navi() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesGastro.Shared.Navi", typeof(Navi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss sich um eine gültige Mailadresse handeln. ähnelt.
        /// </summary>
        public static string AlertMail {
            get {
                return ResourceManager.GetString("AlertMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie oben im Formular eine Personenzahl ein. ähnelt.
        /// </summary>
        public static string AlertPersonenzahl {
            get {
                return ResourceManager.GetString("AlertPersonenzahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte nur Ziffern eingeben. ähnelt.
        /// </summary>
        public static string AlertTelefon {
            get {
                return ResourceManager.GetString("AlertTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhaltsstoffe ähnelt.
        /// </summary>
        public static string Allergene {
            get {
                return ResourceManager.GetString("Allergene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gleichzeitig als unverbindliche Anfrage an den Wirt senden ähnelt.
        /// </summary>
        public static string AnfrageWirt {
            get {
                return ResourceManager.GetString("AnfrageWirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pdf erstellen ähnelt.
        /// </summary>
        public static string BtnPdfErstellenText {
            get {
                return ResourceManager.GetString("BtnPdfErstellenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich bin damit einverstanden, dass meine Angaben verwendet werden, damit auf meine Anfrage reagiert werden kann. Meine Daten werden in keiner Datenbank gespeichert, sie werden lediglich auf das Pdf-Dokument gedruckt, das dem Veranstalter zugeht. ähnelt.
        /// </summary>
        public static string DsvgoText {
            get {
                return ResourceManager.GetString("DsvgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mailadresse ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getränke ähnelt.
        /// </summary>
        public static string Getränke {
            get {
                return ResourceManager.GetString("Getränke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        public static string Impressum {
            get {
                return ResourceManager.GetString("Impressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die insgesamt ähnelt.
        /// </summary>
        public static string Insgesamt {
            get {
                return ResourceManager.GetString("Insgesamt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakt ähnelt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittagstisch ähnelt.
        /// </summary>
        public static string Mittagstisch {
            get {
                return ResourceManager.GetString("Mittagstisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnungszeiten ähnelt.
        /// </summary>
        public static string Öffnungszeiten {
            get {
                return ResourceManager.GetString("Öffnungszeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vielen Dank für Ihr Interesse an unserem Haus. Wir werden uns zeitnah mit Ihnen in Verbindung setzen. ähnelt.
        /// </summary>
        public static string PdfAnsprache {
            get {
                return ResourceManager.GetString("PdfAnsprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personen ähnelt.
        /// </summary>
        public static string Personen {
            get {
                return ResourceManager.GetString("Personen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Auswahl ähnelt.
        /// </summary>
        public static string PlanderPdfHeader {
            get {
                return ResourceManager.GetString("PlanderPdfHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit diesem Service können Sie die zu erwartenden Kosten für eine Veranstaltung berechnen und sich das Ergebnis ausdrucken. Wenn Sie möchten, können Sie Ihre Berechnung auch an den Wirt senden. Dann bitten wir Sie um ein paar Angaben, um Sie kontaktieren zu können. ähnelt.
        /// </summary>
        public static string PlanerBeschreibung {
            get {
                return ResourceManager.GetString("PlanerBeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie zunächst die Anzahl der Personen ein, für die Sie eine Veranstaltung bei uns planen Bitte geben Sie zunächst die Anzahl der Personen ein, für die Sie eine Veranstaltung bei uns planen möchten. ähnelt.
        /// </summary>
        public static string PlanerIntro {
            get {
                return ResourceManager.GetString("PlanerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlanerPdfName {
            get {
                return ResourceManager.GetString("PlanerPdfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefonnummer ähnelt.
        /// </summary>
        public static string PlanerPdfTelefon {
            get {
                return ResourceManager.GetString("PlanerPdfTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geplanter Termin ähnelt.
        /// </summary>
        public static string PlanerPdfTermin {
            get {
                return ResourceManager.GetString("PlanerPdfTermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summe ähnelt.
        /// </summary>
        public static string Planersumme {
            get {
                return ResourceManager.GetString("Planersumme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Räumlichkeiten ähnelt.
        /// </summary>
        public static string Raeumlichkeiten {
            get {
                return ResourceManager.GetString("Raeumlichkeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reservierung ähnelt.
        /// </summary>
        public static string Reservierung {
            get {
                return ResourceManager.GetString("Reservierung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speisekarte ähnelt.
        /// </summary>
        public static string Speisekarte {
            get {
                return ResourceManager.GetString("Speisekarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speisen ähnelt.
        /// </summary>
        public static string Speisen {
            get {
                return ResourceManager.GetString("Speisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über uns ähnelt.
        /// </summary>
        public static string UeberUns {
            get {
                return ResourceManager.GetString("UeberUns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veranstaltungsplaner ähnelt.
        /// </summary>
        public static string Veranstaltungsplaner {
            get {
                return ResourceManager.GetString("Veranstaltungsplaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusammenfassung ähnelt.
        /// </summary>
        public static string Zusammenfassung {
            get {
                return ResourceManager.GetString("Zusammenfassung", resourceCulture);
            }
        }
    }
}
