//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminKontakte
    {
        public int id { get; set; }
        public string AdresseName { get; set; }
        public string AdresseStrasse { get; set; }
        public string AdresseZusatz { get; set; }
        public string AdressePlz { get; set; }
        public string AdresseOrt { get; set; }
        public string Telefon { get; set; }
        public string Telefax { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string GooglePlus { get; set; }
        public string Youtube { get; set; }
        public string Pinterest { get; set; }
        public string Instagramm { get; set; }
        public string Snapchat { get; set; }
        public string Einleitungstext { get; set; }
        public string TextFuerNachricht { get; set; }
        public string AdresseInhaber { get; set; }
        public string GpsKartenDaten { get; set; }
    }
}
