//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class I18n
    {
        public int id { get; set; }
        public int Typ { get; set; }
        public int SprachId { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Ergänzung1 { get; set; }
        public string Ergänzung2 { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string Einheit { get; set; }
        public int AllergenId { get; set; }
    }
}
