//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GastroEntities : DbContext
    {
        public GastroEntities()
            : base("name=GastroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> Benutzer { get; set; }
        public virtual DbSet<Getränke> Getränke { get; set; }
        public virtual DbSet<Speisen> Speisen { get; set; }
        public virtual DbSet<Veranstaltungen> Veranstaltungen { get; set; }
        public virtual DbSet<VeranstaltungenGetränke> VeranstaltungenGetränke { get; set; }
        public virtual DbSet<VeranstaltungenSpeisen> VeranstaltungenSpeisen { get; set; }
        public virtual DbSet<VeranstaltungsGetränke> VeranstaltungsGetränke { get; set; }
        public virtual DbSet<VeranstaltungsSpeisen> VeranstaltungsSpeisen { get; set; }
        public virtual DbSet<LogInLog> LogInLog { get; set; }
        public virtual DbSet<Räume> Räume { get; set; }
        public virtual DbSet<Kategorien> Kategorien { get; set; }
        public virtual DbSet<Mittagstisch> Mittagstisch { get; set; }
        public virtual DbSet<Allergene> Allergene { get; set; }
        public virtual DbSet<AllergeneMittagstischIdSpeiseId> AllergeneMittagstischIdSpeiseId { get; set; }
        public virtual DbSet<AllergeneSpeiseIdSpeiseId> AllergeneSpeiseIdSpeiseId { get; set; }
        public virtual DbSet<I18n> I18n { get; set; }
        public virtual DbSet<AllergeneGetränkeIdSpeiseId> AllergeneGetränkeIdSpeiseId { get; set; }
        public virtual DbSet<AllergeneVeranstaltungsGetränkeIdSpeiseId> AllergeneVeranstaltungsGetränkeIdSpeiseId { get; set; }
        public virtual DbSet<AllergeneVeranstaltungsSpeisenIdSpeiseId> AllergeneVeranstaltungsSpeisenIdSpeiseId { get; set; }
        public virtual DbSet<Öffnungszeiten> Öffnungszeiten { get; set; }
        public virtual DbSet<Reservierungen> Reservierungen { get; set; }
    }
}
