//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservierungen
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Telefonnummer { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Personenzahl { get; set; }
        public Nullable<System.DateTime> Eingabedatum { get; set; }
        public string Nachricht { get; set; }
    }
}
