//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Räume
    {
        public int id { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> MaxPersonen { get; set; }
        public Nullable<decimal> Preis { get; set; }
    }
}
