//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tischbelegungen
    {
        public int id { get; set; }
        public int TischId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Von { get; set; }
        public System.DateTime Bis { get; set; }
    }
}
