//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umfragen
    {
        public int id { get; set; }
        public System.DateTime DatumStart { get; set; }
        public System.DateTime DatumEnde { get; set; }
        public string Typ { get; set; }
        public string Frage { get; set; }
        public string Titel { get; set; }
        public string Einleitung { get; set; }
    }
}
