//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmfrageErgebnisse
    {
        public int id { get; set; }
        public System.DateTime DatumEintrag { get; set; }
        public int UmfrageId { get; set; }
        public string Antwort { get; set; }
        public string IP { get; set; }
    }
}
