//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeranstaltungsGetränke
    {
        public int id { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public string Einheit { get; set; }
        public Nullable<decimal> PreisProEinheit { get; set; }
        public int KategorieGetränke { get; set; }
        public int Sortierung { get; set; }
        public bool IstAktiv { get; set; }
    }
}
