//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veranstaltungen
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Guid { get; set; }
        public string VeranstaltungsDatum { get; set; }
        public System.DateTime EingabeDatum { get; set; }
        public string Personenzahl { get; set; }
        public string SummeSpeisen { get; set; }
        public string SummeGetränke { get; set; }
        public string SUmmeGesamt { get; set; }
    }
}
