//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GastroPages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öffnungszeiten
    {
        public int id { get; set; }
        public int Wochentag { get; set; }
        public string Von1 { get; set; }
        public string Bis1 { get; set; }
        public string Von2 { get; set; }
        public string Bis2 { get; set; }
        public bool IstRuhetag { get; set; }
        public string Ergänzung1 { get; set; }
        public string Ergänzung2 { get; set; }
        public string Ergänzung3 { get; set; }
    }
}
